// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type SensorsDatum struct {
	DataID    int64
	Value     float64
	Unit      sql.NullString
	Id1       int32
	Id2       string
	ReadAt    time.Time
	CreatedAt time.Time
}
